Module 9 tasks 1-2
js-tasks-ru/jsbasic-20240321_timofeevdn28 pull request #10
Opened 2024-05-02 08:25 UTC by timofeev-28

2024-05-02 08:25 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-05-02 15:38 UTC, SinimaWath requested changes

2024-05-02 15:38 UTC, SinimaWath commented on 9-module/2-task/index.js
> +    return new Promise((resolve) => { resolve(); });
В этом коде нет необходимости, так как по-умолчанию async функция возвращает promise.

так что строчку можно просто убрать

2024-05-02 15:51 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-05-03 11:43 UTC, SinimaWath approved these changes
Все круто!

2024-05-03 11:44 UTC, merged