added 1-5 tasks from module-3
js-tasks-ru/jsbasic-20240321_timofeevdn28 pull request #4
Opened 2024-04-02 15:08 UTC by timofeev-28

2024-04-02 15:09 UTC, jsru commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-02 19:56 UTC, SinimaWath approved these changes, later dismissed
Все круто!

2024-04-03 14:20 UTC, timofeev-28 commented
Понял, спасибо!!!

2024-04-05 11:13 UTC, jsru-1 commented
Добавляю преподавателя (@SinimaWath) для код-ревью.

2024-04-05 14:51 UTC, SinimaWath requested changes
Не нужно удалять, добавленные задачи из других модулей :) Верни их плиз

2024-04-05 16:04 UTC, closed without merging